### ISSUE TITLE
About styles - phantom

### ISSUE THREAD

**Issue by 736mo** [SublimeLinter/SublimeLinter-clang#14] opened 2023-06-17 05:26 UTC
```json
"styles": [
    {
        "scope": "region.yellowish markup.warning.sublime_linter",
        "types": ["warning"],
        "priority": 1,
        "icon": "circle",
        "mark_style": "outline",
        "annotation": "{code}",
        "phantom": "{msg}"
    },
    {
        "scope": "region.redish markup.error.sublime_linter",
        "types": ["error"],
        "priority": 1,
        "icon": "circle",
        "mark_style": "outline",
        "annotation": "{code}",
        "phantom": "{msg}"
    }
],
```

No message below the warning text (an example):
![](https://raw.githubusercontent.com/736mo/Picture/main/QQ%E5%9B%BE%E7%89%8720230617132448.png)

**Comment by kaste** [comment] 2023-06-17 22:52
Yeah, that it actually intended behavior.  As long as there are "errors" we don't also show phantoms for "warnings" or other types.  There should be probably a setting for this, but there is none yet.  (This was at least mentioned in the release notes; actually don't know if this is also documented somewhere, preferable right in the settings.)

But if you switch `highlights.start_hidden` (see the help in the settings file) all phantoms are drawn or toggled.

**Comment by kaste** [comment] 2023-10-16 11:03
Closing as this works as implemented

**Closed as completed by kaste** 2023-10-16 11:03 UTC
